-- require("config.theme")
require("config.options")
require("config.session")
require("config.diagnostics")
require("config.lsp")
require("config.autocmds")
require("config.keys")
require("config.packui")
require("config.ui2")
